# Generated by Django 4.1.6 on 2023-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(default='', max_length=20, verbose_name='班级')),
                ('names', models.CharField(default='', max_length=20, verbose_name='姓名')),
            ],
        ),
    ]
