# Generated by Django 4.1.6 on 2023-02-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tap',
            table='tap',
        ),
    ]
