# Generated by Django 4.1.6 on 2023-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winshop', '0003_tap_stud_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='伪删除'),
        ),
    ]
