# Generated by Django 4.1.6 on 2023-03-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winshop', '0005_nmobes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nmobes',
            table='nmobes',
        ),
    ]
