# Generated by Django 4.1.6 on 2023-03-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winshop', '0006_alter_nmobes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmobes',
            name='answer',
            field=models.IntegerField(default=None, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='nmobes',
            name='ask',
            field=models.CharField(default=None, max_length=100, verbose_name='姓名'),
        ),
        migrations.CreateModel(
            name='Mouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adk', models.CharField(default=None, max_length=100, verbose_name='姓名')),
                ('anbbr', models.IntegerField(default=None, verbose_name='年龄')),
                ('ddr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='winshop.nmobes')),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'Mouth',
                'managed': True,
            },
        ),
    ]
